module.exports = { ActionTypes: {
  JUGAR_POSICION: "JUGAR_POSICION",
  REINICIAR_JUEGO: "REINICIAR_JUEGO",
  REINICIAR_MARCADORES: "REINICIAR_MARCADORES",
  NUEVO_TAMAÑO: "NUEVO_TAMAÑO" },
  CHANGE_EVENT: 'change',
  JUGADORX : "jugador 1 - las X",
  JUGADOR0 : "jugador 2 - los 0"
};
